# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDefaultSuite():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test1AccountNoCannotBeEmpty(self):
        self.driver.get("https://demo.guru99.com/V4/manager/deleteAccountInput.php")
        self.driver.set_window_size(908, 730)
        self.driver.find_element(By.NAME, "accountno").click()

    def test_test2AccountNoMustBeNumeric(self):
        self.driver.get("https://demo.guru99.com/V4/manager/deleteAccountInput.php")
        self.driver.set_window_size(908, 731)
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("Acc123")

    def test_test3AccountNoCantHaveSpecialCharacter(self):
        self.driver.get("https://demo.guru99.com/V4/manager/deleteAccountInput.php")
        self.driver.set_window_size(908, 731)
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("123!@3#")

    def test_test4AccountNoCantHaveBlankSpace(self):
        self.driver.get("https://demo.guru99.com/V4/manager/deleteAccountInput.php")
        self.driver.set_window_size(908, 731)
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("123 12")

    def test_test5FirstCharacterCannotBeSpace(self):
        self.driver.get("https://demo.guru99.com/V4/manager/deleteAccountInput.php")
        self.driver.set_window_size(908, 727)
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys(" ")
        self.driver.find_element(By.NAME, "accountno").send_keys(" ")

    def test_test6ValidAccountNo(self):
        self.driver.get("https://demo.guru99.com/V4/manager/deleteAccountInput.php")
        self.driver.set_window_size(908, 727)
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("143932")
        self.driver.find_element(By.NAME, "AccSubmit").click()
        assert self.driver.switch_to.alert.text == "Do you really want to delete this Account?"
        self.driver.switch_to.alert.accept()

    def test_test7InvalidAccountNo(self):
        self.driver.get("https://demo.guru99.com/V4/manager/deleteAccountInput.php")
        self.driver.set_window_size(908, 727)
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("12345")
        self.driver.find_element(By.NAME, "AccSubmit").click()

    def test_test8ResetButton(self):
        self.driver.get("https://demo.guru99.com/V4/manager/deleteAccountInput.php")
        self.driver.set_window_size(908, 727)
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("qwer 12345")
        self.driver.find_element(By.NAME, "res").click()

